# Generated by Django 5.1.4 on 2025-11-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_collector', '0002_alter_article_options_article_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
