# Generated by Django 5.1.4 on 2025-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_collector', '0003_feed_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='config',
        ),
        migrations.AddField(
            model_name='feed',
            name='author_field',
            field=models.CharField(default='dc:creator', max_length=100),
        ),
        migrations.AddField(
            model_name='feed',
            name='call_frequency',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='feed',
            name='categories_field',
            field=models.CharField(default='category', max_length=100),
        ),
        migrations.AddField(
            model_name='feed',
            name='content_field',
            field=models.CharField(default='content:encoded', max_length=100),
        ),
        migrations.AddField(
            model_name='feed',
            name='date_format',
            field=models.CharField(default='%a, %d %b %Y %H:%M:%S %Z', max_length=100),
        ),
        migrations.AddField(
            model_name='feed',
            name='description_field',
            field=models.CharField(default='description', max_length=100),
        ),
        migrations.AddField(
            model_name='feed',
            name='extract_full_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='parser_type',
            field=models.CharField(choices=[('generic', 'Generic Parser')], default='generic', max_length=50),
        ),
        migrations.AddField(
            model_name='feed',
            name='published_field',
            field=models.CharField(default='pubDate', max_length=100),
        ),
        migrations.AddField(
            model_name='feed',
            name='title_field',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='feed',
            name='url_field',
            field=models.CharField(default='link', max_length=100),
        ),
    ]
