# Generated by Django 5.1.4 on 2025-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_collector', '0004_remove_feed_config_feed_author_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_format',
            field=models.CharField(default='%a, %d %b %Y %H:%M:%S %z', max_length=100),
        ),
    ]
