# Generated by Django 5.1.4 on 2025-11-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_collector', '0005_alter_feed_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='next_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
