# Generated by Django 5.1.4 on 2025-11-13 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_collector', '0006_feed_next_fetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='author_field',
            field=models.CharField(blank=True, default='dc:creator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='categories_field',
            field=models.CharField(blank=True, default='category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='content_field',
            field=models.CharField(blank=True, default='content:encoded', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_format',
            field=models.CharField(blank=True, default='%a, %d %b %Y %H:%M:%S %z', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description_field',
            field=models.CharField(blank=True, default='description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='next_fetch',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feed',
            name='published_field',
            field=models.CharField(blank=True, default='pubDate', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title_field',
            field=models.CharField(blank=True, default='title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url_field',
            field=models.CharField(blank=True, default='link', max_length=100, null=True),
        ),
    ]
